### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Kushma** [AVSystem/Anjay-java#2]
Hi,
I am following the below steps in order to compile Anjay java in my Windows system.

git clone https://github.com/AVSystem/Anjay-java.git
Open Android Studio and import the project.
Open the terminal and run this command "./gradlew -Pandroid :library:build", I see the below errors.
[Anjay_java1.txt](https://github.com/AVSystem/Anjay-java/files/9054368/Anjay_java1.txt)
Followed the below steps on Linux:

git clone https://github.com/AVSystem/Anjay-java.git
git submodule update --init --recursive
Set the SDK and NDK path and run "./gradlew :library:build".
I am seeing the below error:
[Anjay_java2.txt](https://github.com/AVSystem/Anjay-java/files/9054629/Anjay_java2.txt)
[Anjay_java3.txt](https://github.com/AVSystem/Anjay-java/files/9054701/Anjay_java3.txt)
I have followed the below steps too:
cd native-library/deps/anjay
git checkout 2.15.0
cd ../../..
git add -u
git submodule update --init --recursive

Can you please help me with this issue? Also, can I get more steps so I can compile the code?
Is there a specific Java version that is needed for Anjay java to compile?
Can I compile Anjay java in Windows and Linux?

**Comment by Mierunski** [comment]
Closing as #3 is more recent
